version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: nft_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: nft_capture_game
      MYSQL_USER: nft_user
      MYSQL_PASSWORD: nft_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data: