[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

# Network configurations
[rpc_endpoints]
monad_testnet = "https://testnet-rpc.monad.xyz"

# Chain configurations
[etherscan]
monad_testnet = { key = "${MONAD_API_KEY}", url = "https://testnet.monadexplorer.com/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
